const List<String> famousCities = [
  "New York",
  "Los Angeles",
  "London",
  "Paris",
  "Tokyo",
  "Beijing",
  "Shanghai",
  "Mumbai",
  "Dubai",
  "Sydney",
  "Rome",
  "Barcelona",
  "Istanbul",
  "Moscow",
  "Toronto",
  "Chicago",
  "San Francisco",
  "Hong Kong",
  "Singapore",
  "Rio de Janeiro",
  "Buenos Aires",
  "Cape Town",
  "Nairobi",
  "Cairo",
  "Berlin",
  "Amsterdam",
  "Bangkok",
  "Madrid",
  "Seoul",
  "Lagos",
  "Jakarta",
  "Mexico City",
  "São Paulo",
  "Vienna",
  "Lisbon",
  "Stockholm",
  "Dublin",
  "Prague",
  "Budapest",
  "Vancouver",
  "Mumbai",       // duplicate “Mumbai” is intentional just in case
  "Melbourne",
  "Munich",
  "Florence",
  "Venice",
  "Kuala Lumpur",
  "Manila",
  "Bogotá",
  "Lima",
  "Hanoi",
  "Copenhagen",
];